## IIR滤波器设计脉冲响应不变法

利用脉冲响应不变变换法，把下列模拟域的模拟滤波器转换为数字滤波器，采样周期$T=1$
$$H(s)=\frac{s+1}{s^2+5s+6}$$

In [1]:
#导入需要的库
import numpy as np
from scipy import signal

#模拟滤波器传递函数
b_analog = np.array([1,1]) #分子系数向量
a_analog = np.array([1,5,6]) #分母系数向量
T = 1 #采样周期

#脉冲响应不变法
r,p_analog,k = signal.residue(b_analog,a_analog) 
#r is coefficient, p_analog is pole in analog
p_digital = np.exp(p_analog*T) #p_digital is pole in digital
a_digital,b_digital = signal.invresz(r,p_digital,k)
a_digital,b_digital #display values of denominator and numerator

(array([ 1.       , -0.2208835]),
 array([ 1.        , -0.18512235,  0.00673795]))

In [4]:
#导入需要的库
import numpy as np
from scipy import signal


#脉冲响应不变法
def impulse_IIR(den_analog,num_analog,T):
    #den_analog:模拟滤波器的分母系数向量
    #num_analog:模拟滤波器的分子系数向量
    #T:采样周期
    r,p_analog,k = signal.residue(den_analog,num_analog) 
    #r 对应极点的余数, p_analog 模拟滤波器的极点
    p_digital = np.exp(p_analog*T) #p_digital 数字滤波器的极点
    num_digital,den_digital = signal.invresz(r,p_digital,k)
    return num_digital,den_digital #返回数字滤波器的分子和分母系数向量


#给定模拟滤波器的传递函数
b_analog = np.array([1,1]) #分子系数向量
a_analog = np.array([1,5,6]) #分母系数向量
T = 1 #采样周期
a,b = impulse_IIR(b_analog,a_analog,T)
a,b

(array([ 1.       , -0.2208835]),
 array([ 1.        , -0.18512235,  0.00673795]))

根据打印结果，可以得到该模拟域滤波器对应的Z域传递函数为
$$H(z)=\frac{1-0.2208835z^{-1}}{1-0.18512235z^{-1}+0.00673795z^{-2}}$$

**invresz：Compute b(z) and a(z) from partial fraction expansion.**

- 函数用法：b,a = scipy.signal.invresz(r, p, k, tol=0.001, rtype='avg')

**输入参数：**
1. r是对应极点的余数；
2. p是极点，相等的极点必须相邻；
3. k是系数；
4. tol是两根被认为相等前的距离容差，默认为0.001；
5. rtype是当多个根之间距离小于容差tol时，最后呈现的方式，默认为avg，。
**输出参数：**
1. b是数字滤波器的分子系数；
2. a是数字滤波器的分母系数。